language: android

jdk:
 - oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew clean check

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "XE5H1J5oRpasEnuCAB0BjdJLeE7WQTMUJuMe2GvuglhuBSL/BvWTAkQNgif/eKyO0+qSDVteapuntavHW2qexJneh43cDfKctERWfURpjA8m9CdncAA0paT+WPa3IQsKrUlpcTq5oQpamKFAJC004DVf3lWbi3a0vaY8HFvwp8glyOYeURGuSdrEx+8DhziQGVgOZC8c4GhHAZ22DwG08ak8//Dbrj6pwag6iYDVwvElTg1hZajCz/WCQ4g+NZ7yxNQigfDe5hlL2Bn443YSA8aC7PKlFuMmG4cAQtHaR3Ml/tYJoMrkTta60z4lxVIF8a0GazcMu5CSl++N0Jxv7hF8GcxEoojNeNIzy4TTuUjS3LJwIHlkxCTVMG3fe34soKU1hmcmYx/5mut0sC/Mr6rHcmLk5YKegrLel5ZHQ9wPvyzfC6H/jcBiZ/uUa2Ak6RYhDO9vp1UFz3GPr4bJOan2yTOEZ7pYf+jy+SzqlYKlFuEVFj/OlSVe0dc3OIOnxYMBYIFS8G6UPUlpKieOvFhOGPNudYctubJBAROi2pGUTKWJkhHlGUXqzkS/R2KSVZ8HAY5WW0J7F9faQE8zxJ+H2aeVdotC5C7CGIfiWZ96rcNSJxR+hkchRuyzit04iOygQxuOSp2Jnh8+WYvZAJtsi1nzxAaGMnr4KEvWF9U="
    - secure: "FXlZ9jlShNyHSTi5NTDH9GB0uElLO7+Cx7/wQPgylh81Rqrk7TAbGJtLyOjwBbaWeQObCWYl1BJbNfltkX5v2BKB8WjxrNexPSB88JBHZKMJVqlpvsdUEJFkD5DUyJURSaiX8quopQaEq+F4QYjJpGrM6aux6UdnVRL68cY8+gU0G9sZ08Dz4xdVuFGA8qmrUsLCEba3dNHUOJfnAMhep91IgmC2/v7pZbmT+4prupSX40ke/Rq5PS42+c3Qs3eZXyNzxUW25JItksyBMOIPe2INl6Duged/ykhcgBqQo6nEnZ8nqt31/G/a701ZbQ4KaQZ4czpnjC60hG37SaTTWfjNavAVA7TUe6+qb31iwKtmVCIvO2Gfsoh0y6OpesWQJYobXCthUZVSIivfy4QIO4tIx7BJIq/ydhmYBmdkjkPR3eEYHk6OOTUqDhTNAmZsZgDh+UmyH3XHZ6u1ltcBW24LrP337hUxHc+QPX2GS1g7FHg4BTeE/KqG35MER3yvQleKOw9IOyo2ReCL04kAfYUKGw78aGQlZGCeD3+wxCuY3HWx5w9WIIRT3Wv5I8r/PbxkLUei5Kmn3ehgG9O/r664jDdnZ4t48bH6sLE/5aFzrgS/DHtczWn74ve8Ut/OKWQUG0sXUQES4ewqa+ZiUbVUJfaXr1Ihejdpx8NLwMs="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
